<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 15 Jul 2020 20:22:00 +0000
 */
$conf['title'] = 'Contract Manager v2.0';
$conf['lang'] = 'en';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
