# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 15 Jul 2020 20:22:00 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

muianelson:$1$8qN3c2WH$xPJ4SM57Y0v2V4Lx34SNm/:Nelson Muia:muianelson@gmail.com:admin,user
